version: '3.5'

services:
  oph:
    build: ${PWD}
    image: abishekmuthian/open-payment-host
    container_name: oph-container
    command: /open-payment-host
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}:/build