version: '3.8'

services:
  oph:
    build: ${PWD}
    image: abishekmuthian/open-payment-host
    container_name: oph-container
    ports:
      - '443:443'
    volumes:
      - ${PWD}:/home/default/build
      - /home/default/build/exec
    command: /home/default/build/exec/open-payment-host
        
