version: "3.8"

services:
  oph:
    image: abishekmuthian/open-payment-host:latest
    container_name: oph-container
    command: /home/default/build/exec/open-payment-host
    ports:
      - "3000:3000"
    volumes:
      - /data/secrets:/home/default/build/data/secrets
      - /data/db:/home/default/build/data/db
      - /data/log:/home/default/build/data/log
      - /data/public/assets/images/products:/home/default/build/data/public/assets/images/products
