CREATE TABLE IF NOT EXISTS products (
    id integer primary key autoincrement,
    created_at text,
    updated_at text,
    tweeted_at text,
    status integer,
    name text,
    url text,
    featured_image text,
    s3_bucket text,
    s3_key    text,
    rank integer,
    summary text,
    description text,
    user_id integer,
    user_name text,
    points integer,
    comment_count integer,
    emailed_at text,
    all_time_page_views integer,
    all_time_top3_countries text,
    seven_days_page_views integer,
    seven_days_top3_countries text,
    insights_updated text,
    subscribers integer,
    thirty_days_page_views integer,
    thirty_days_top3_countries text,
    shared boolean,
    stripe_price text,
    mailchimp_audience_id text,
    square_price text,
    schedule text,
    square_subscription_plan_Id text,
    paypal_price text
);

CREATE TABLE IF NOT EXISTS users (
    id integer primary key autoincrement,
    created_at text,
    updated_at text,
    status integer,
    role integer,
    email text,
    password_hash text,
    password_reset_at text,
    password_reset_token text
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id integer primary key autoincrement,
    created_at text,
    updated_at text,
    txn_id text,
    txn_type text,
    transaction_subject text,
    business text,
    custom text,
    invoice text,
    receipt_ID text,
    first_name text,
    handling_amount real,
    item_number integer,
    item_name text,
    last_name text,
    mc_currency text,
    mc_fee real,
    mc_gross real,
    payer_email text,
    payer_id text,
    payer_status text,
    payment_date text,
    payment_fee real,
    payment_gross real,
    payment_status text,
    payment_type text,
    protection_eligibility text,
    quantity integer,
    receiver_id text,
    receiver_email text,
    residence_country text,
    shipping real,
    tax real,
    address_country text,
    test_ipn integer,
    address_status text,
    address_street text,
    notify_version real,
    address_city text,
    verify_sign text,
    address_state text,
    charset text,
    address_name text,
    address_country_code text,
    address_zip integer,
    subscr_id text,
    user_id integer,
    test_pdt integer
);